# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4467671505f36e445e72ef0ccbb239fc208e09f40f8bd4d7aafb08c7eee3b888e1f397df30d503ecae89a14b4ef5c42ebf0ee84032a79e88a01fda29de430754

test:
  secret_key_base: 1b72e259d2f478f8f0619f5067ecdcdfd3b0887edc8eb5c08875f17a4e5daf3a70f3da71175d99f4499601609e49e73160b7d491af1d41f07708ede2fc5d6927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
